export const SET_SHOW_LOADING_MODAL = "SET_SHOW_LOADING_MODAL";
export const SET_SHOW_AUTH_MODAL = "SET_SHOW_AUTH_MODAL";
export const SET_MODAL = "SET_MODAL";
export const HANDLE_SESSION = "HANDLE_SESSION";
