export const SET_CONNECTED = "SET_CONNECTED";

export const UPDATE_ONLINE_USERS = "UPDATE_ONLINE_USERS";
export const UPDATE_MESSAGES = "UPDATE_MESSAGES";

export const SET_SHOW_LOGIN_MESSAGE = "SET_SHOW_LOGIN_MESSAGE";
